version: "3"

services:
  api:
    build: ./backend
    volumes:
      - ./backend:/app
    env_file: ./backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:11.5
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file: ./backend/.env
    ports:
      - "5432:5432"